FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.8 as builder

RUN install_packages git bluetooth bluez bluez-firmware bluez-hcidump libbluetooth-dev libudev-dev  
RUN python3 -m pip install enum34

RUN git clone https://github.com/iayanpahwa/PyBeacon.git
RUN cd PyBeacon && python3 setup.py install

ENV ADVERTISE='TRUE'
ENV URL='https://hub.balena.io'

WORKDIR /usr/src/app
COPY main.sh main.sh
CMD [ "/bin/bash", "main.sh" ]